sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t septiapermana/learn-deploy-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true septiapermana/learn-deploy-docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "learn-deploy-docker-react"
  env: "learn-deploy-docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-590183767841"
  bucket_path: "learn-deploy-docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
